name    = App-ClusterSSH
author  = Duncan Ferguson <duncan_j_ferguson@yahoo.co.uk>
license = Perl_5
copyright_holder = Duncan Ferguson
copyright_year   = 2018

;----------------------------------------
; Start from a standard baseline
;----------------------------------------
[@Filter]
bundle = @Basic
remove = MakeMaker
remove = Readme

;----------------------------------------
; Build/install
;----------------------------------------
[ModuleBuild::Custom]
mb_class = App::ClusterSSH::Build

[InstallGuide]

;----------------------------------------
; File pruning/customization
;----------------------------------------
[PruneFiles]
match = ^bin/
match = \.bak$
match = ^Build\.PL\.

;----------------------------------------
; Versioning + changelog
;----------------------------------------
[VersionFromModule]
[PkgVersion]
[NextRelease]
[CheckChangeLog]

;----------------------------------------
; Prereqs
;----------------------------------------
[AutoPrereqs]

; optional prereqs - only used if they are installed
[Prereqs / RuntimeRecommends]
Sort::Naturally = 1.03

; Author prereqs
; authordep Pod::Coverage::TrustPod
; authordep Test::CPAN::Changes

;----------------------------------------
; Quality/tests
;----------------------------------------
[PerlTidy]
perltidyrc = t/perltidyrc

[ExtraTests]
; Disabled for the moment
;[Test::Perl::Critic]
[PodCoverageTests]
[PodSyntaxTests]

;----------------------------------------
; Metadata
;----------------------------------------
[MetaResources]
homepage        = https://github.com/duncs/clusterssh/wiki
bugtracker.web  = https://github.com/duncs/clusterssh/issues
repository.web  = https://github.com/duncs/clusterssh
repository.type = git
; these two custom ones cause errors
;Ci.web          = https://travis-ci.org/duncs/clusterssh
;Coverage.web    = https://coveralls.io/github/duncs/clusterssh

;----------------------------------------
; Generate README into the repository
;----------------------------------------
[Run::BeforeBuild]
run = bin_PL/cssh --generate-pod | pod2text > README

;----------------------------------------
; Release flow
;----------------------------------------
[TestRelease]
[ConfirmRelease]
[UploadToCPAN]

[EmailNotify]
to   = duncan_j_ferguson@yahoo.co.uk
from = duncan_j_ferguson@yahoo.co.uk

[@Git]
