#!/usr/bin/perl
use strict;
use warnings;

use FindBin;
use lib $FindBin::Bin. '/../lib';
use lib $FindBin::Bin. '/../lib/perl5';
use App::ClusterSSH;

my $app = App::ClusterSSH->new();

$app->options->add_common_ssh_options;
$app->options->add_common_session_options;

$app->add_option(
    spec => 'freddo|z',
    help => $app->loc("Some help output"),
);

$app->run();

1;
