#!/bin/ksh
# $Id$
#
# Script:
#   $RCSfile$
#
# Usage:
#   <Normal usage of this script - how/when is it run>
#
# Options:
#   <Standard options which this script accepts>
#   -v  (O)  Verbose mode - prints out informational data
#
#   -?  (O) Usage and help for this script
#
# Parameters:
#   <Specific parameters for the script>
#   -p  (O)  process name (if not provided, use configuration file)
#
# Purpose:
#   <Brief description of the scripts purpose>
#
# Processing:
#   Detailed description of the process flow - virtually the pseudo code>
#
# Dependencies:
#   <list of any know dependancies which this script requires>
#
# Limitations:
#   <Any known or perceived limitations with the script - be honest now !!>
#
# Enhancements:
#   <Any future enhancements which would either make this script
#   more useful or fix any know limitations>
#
############################################################################
# $Log$
# Revision 1.7  2004/08/16 13:11:16  duncan_ferguson
# change patch of package destination
#
# Revision 1.6  2004/06/02 08:54:20  duncan_ferguson
# remove unncessary rm of pod temp files
#
# Revision 1.5  2004/05/04 15:02:27  duncan_ferguson
# Remove tar file creation for sf.net in leiu of 'release'
#
# Revision 1.4  2004/04/20 12:45:43  duncan_ferguson
# Amended to include cchp in tarball
#
# Revision 1.3  2004/04/06 11:42:13  duncan_ferguson
# Remove setuid stuff for version 2.0
#
# Revision 1.2  2004/01/28 13:40:31  duncan_ferguson
# also create cssh man in plain text for web site upload
#
# Revision 1.1  2004/01/28 12:40:42  duncan_ferguson
# inital version of in-house prject script
# NOT FOR GENERAL CONSUMPTION
#
############################################################################
VERSION=$(
	echo '$Revision$ ($Date$)' | \
	sed -e 's/$Revision: //' \
			-e 's/$Date: //' \
			-e 's/ \$//g'
)

chmod +x make_package
./make_package -n EGGcssh

cp -rp EGGcssh ~/pkgs
