#!/bin/ksh

if [ -z "$1" ]; then
	echo "WARNING - version not given"
	exit 1
fi

TAR=clusterssh-$1.tar.gz
RPM=clusterssh-$1-1.i386.rpm
RPMPATH=/usr/src/redhat/RPMS/i386/

if [ ! -r $TAR ]
then
	echo "WARNING: cannot read file $TAR"
	exit 1
fi 

if [ ! -r $RPMPATH/$RPM ]
then
	echo "WARNING: cannot read file $RPMPATH/$RPM"
	exit 1
fi

scp $TAR $RPMPATH/$RPM shell-ssh.sf.net:
ssh shell-ssh.sf.net ncftpput upload.sourceforge.net incoming $TAR $RPM
