name: CI test builds

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - latest
          - 5.40
          - 5.38
          - 5.36
          - 5.34
          - 5.32
          - 5.30
          - 5.28
          - 5.26
          - 5.24
          - 5.22
          - 5.20
          - 5.18
          - 5.16
        include:
          - perl-version: '5.38'
            os: ubuntu-latest
            coverage: true
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    name: Perl ${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Regular tests
        if: ${{ !matrix.coverage }}
        run: |
          cpanm -n -f Pod::Coverage::TrustPod Test::Perl::Critic Test::Pod::Coverage Test::Pod
          perl Build.PL
          perl Build test
        env:
          RELEASE_TESTING: 1
          AUTHOR_TESTING: 1
      - name: Coverage tests
        if: ${{ matrix.coverage }}
        run: |
          cpanm -n -f Pod::Coverage::TrustPod Test::Perl::Critic Test::Pod::Coverage Test::Pod
          perl Build.PL
          perl Build test
        env:
          COVERAGE: 1
          RELEASE_TESTING: 1
          AUTHOR_TESTING: 1
